export const moralteile = {
  subjekt: [
    "Verantwortung ist",
    "Demokratie ist",
    "Geld ist",
    "Liebe ist",
    "Betrug ist",
    "Freiheit ist",
    "Denken ist",
    "Selbstlosigkeit ist",
    "Egoismus ist",
    "Moral ist",
    "Glück ist",
    "Konsum ist",
    "Schicksal ist",
    "das Leben ist",
    "Unabhängigkeit ist",
    "Gerechtigkeit ist",
    "der Tod ist",
    "Umweltschutz ist",
    "das Fernsehen ist",
    "ein Seitensprung ist",
    "Gewalt ist",
    "der Sinn des Lebens ist",
    "Leistung ist",
    "Hass ist",
    "Eifersucht ist",
    "die Kunst ist",
    "Religion ist",
    "die Jugend ist",
    "Hoffnung ist",
    "Frieden ist",
    "Ehe ist",
    "Alles ist",
    "Freundschaft ist",
    "Armut ist",
    "Emanzipation ist",
    "eine Diät ist",
    "Angst ist",
    "Ungerechtigkeit ist",
    "Rassismus ist",
    "Humor ist",
    "Deutscher Rap ist",
    "die Lügenpresse ist",
    "Fortpflanzung ist",
    "Schwiegereltern sind",
    "der Sittenverfall ist",
    "unser Schulsystem ist",
    "die Gentrifizierung ist",
    "ein letztes Bier ist",
    "Digitalisierung ist",
    "Datenschutz ist",
    "Künstliche Intelligenz ist",
    "Cancel Culture ist",
    "Patriotismus ist",
    "Globalisierung ist",
    "Achtsamkeit ist",
    "Klimawandel ist",
  ],
  adverb: [
    "letztlich",
    "sozusagen",
    "am Ende des Tages",
    "quasi",
    "genau genommen",
    "wirklich",
    "leider",
    "zum Glück",
    "durch die Blume gesagt",
    "rückblickend",
    "voraussichtlich",
    "unter Umständen",
    "erwiesenermaßen",
    "gelinde gesagt",
    "streng genommen",
    "unterm Strich",
    "in gewisser Hinsicht",
    "für viele",
    "unleugbar",
    "von rechts wegen",
    "primär",
    "irgendwie",
    "sicherlich",
    "von außen betrachtet",
    "schon lange nicht mehr",
    "heutzutage",
    "tatsächlich",
    "in Wahrheit",
    "in Zukunft",
    "bei aller Liebe",
    "praktisch",
    "allenfalls",
    "stückweise",
    "schließlich",
    "an und für sich",
    "bei Lichte gesehen",
    "unwiderleglich",
    "mitnichten",
    "vor allem",
    "auch für Hartgesottene",
    "traurigerweise",
    "für besorgte Bürger",
    "wie man hört",
    "in diesem Sinne",
    "unter Drogeneinfluss",
    "menschlich gesehen",
    "theoretisch",
    "für unsereins",
    "ganz objektiv",
    "in anderen Kulturkreisen",
    "ironischerweise",
    "im Grunde",
    "mutmaßlich",
    "zeitweise",
    "im Kern",
    "über weite Strecken",
    "punktuell",
  ],
  conclusion: [
    "die Basis des Zusammenlebens",
    "eine gesellschaftliche Pflicht",
    "der Anfang allen Übels",
    "das, wofür es sich zu leben lohnt",
    "falsch",
    "zutiefst menschlich",
    "kein Kavaliersdelikt mehr",
    "völlig überschätzt",
    "völlig unterschätzt",
    "immer Gabe und Aufgabe zugleich",
    "mit Vorsicht zu genießen",
    "fragwürdig",
    "existenzgefährdend",
    "der Schlüssel zum Glück",
    "eine Frage des Anstands",
    "jedem selbst überlassen",
    "geil",
    "völlig willkürlich",
    "immer schon vorherbestimmt",
    "alles, was wir haben",
    "ein großes Privileg",
    "nicht machbar",
    "unsere Rettung",
    "eine Katastrophe",
    "der Anfang vom Ende",
    "noch das geringste Übel",
    "nicht grundfalsch",
    "eine Illusion",
    "unterstes Niveau",
    "ein Geschenk Gottes",
    "bedeutungslos",
    "völlig überholt",
    "doch nur relativ",
    "nur die Spitze des Eisbergs",
    "eine große Enttäuschung",
    "erst der Anfang",
    "völlig unabdingbar",
    "echt daneben",
    "eine große Chance",
    "der erste Schritt zur Besserung",
    "das Ziel allen Strebens",
    "eine Frage des richtigen Tons",
    "alles, was uns bleibt",
    "eine Schwäche",
    "schlimmer als der Tod",
    "ein fataler Fehler",
    "besser als Sex",
    "mein Trost und Halt",
    "nichts wert",
    "eine Zumutung",
    "moralisch geboten",
    "eine Frage der Perspektive",
    "kaum zu fassen",
    "rasch vergänglich",
    "auf lange Sicht unvermeidlich",
  ],
};
