export const provokationen = [
  "Schülerinnen und Schüler lernen heutzutage nur, um gute Noten zu bekommen, nicht um wirklich etwas zu lernen.",
  "Schülerinnen und Schüler sind zu sehr von ihren Smartphones abgelenkt, um richtig zu lernen.",
  "LehrerInnen sollten Schülerinnen und Schüler nicht zwingen, bestimmte Fächer zu lernen, die sie nicht interessieren.",
  "Schülerinnen und Schüler sollten nicht nur auswendig lernen, sondern auch kritisches Denken und Problemlösungsfähigkeiten entwickeln.",
  "Das Schulsystem ist veraltet und sollte grundlegend reformiert werden.",
  "Das Schulsystem bevorzugt bestimmte Schülergruppen und diskriminiert andere.",
  "Schülerinnen und Schüler sollten selbst entscheiden können, wie sie am besten lernen und welche Fächer sie belegen möchten.",
  "Es gibt keinen Gott.",
  "Der Glaube an Gott ist das Beste, was der Mensch haben kann.",
  "Es gibt viele Wege zur Erleuchtung, nicht nur den christlichen Weg.",
  "Religionen sind ein Relikt aus der Vergangenheit und haben heute keine Bedeutung mehr.",
  "Das Universum ist unendlich und es gibt unendlich viele Welten mit intelligentem Leben.",
  "Die Wissenschaft wird irgendwann alle Geheimnisse des Universums lüften.",
  "Das Universum ist das Werk eines Schöpfers, der sich jedoch nicht in unser Leben einmischt.",
  "Es gibt kein Leben nach dem Tod.",
  "Jeder Mensch hat eine Bestimmung im Leben, die er selbst finden muss.",
  "Die Welt ist ein Spiel, das von höheren Wesen kontrolliert wird.",
  "Die menschliche Rasse wird irgendwann von künstlicher Intelligenz ersetzt werden.",
  "Der freie Wille ist eine Illusion.",
  "Es gibt kein Gut oder Böse, nur verschiedene Perspektiven.",
  "Die Welt ist ungerecht und es gibt keinen höheren Plan, der das ändern wird.",
  "Die Menschheit ist dazu bestimmt, den Planeten zu zerstören.",
  "Die Natur hat ein Bewusstsein und eine Seele.",
  "Die Bibel ist ein Buch voller Mythen und Legenden, die nicht wörtlich genommen werden sollten.",
  "Das Leben hat keinen Sinn.",
  "Der Klimawandel wird dazu führen, dass die meisten Küstenstädte der Welt innerhalb der nächsten 50 Jahre unter Wasser stehen werden.",
  "In Zukunft wird die künstliche Intelligenz so mächtig sein, dass sie die Kontrolle über die meisten Aspekte des menschlichen Lebens übernehmen wird.",
  "Die fortschreitende Automatisierung wird dazu führen, dass Millionen von Arbeitsplätzen wegfallen werden und eine massive Arbeitslosigkeit entstehen wird.",
  "Die zunehmende globale Ungleichheit wird zu sozialen Unruhen und gewaltsamen Konflikten führen, die die Welt destabilisieren werden.",
  "Die fortschreitende technologische Entwicklung wird es ermöglichen, Menschen genetisch zu modifizieren und zu verbessern, was zu einer neuen Form des Eugenismus führen könnte.",
  "Die menschliche Überbevölkerung wird dazu führen, dass die Ressourcen der Erde immer knapper werden und es zu Verteilungskämpfen kommt.",
  "Der Terrorismus wird weiterhin ein ernsthaftes Problem sein und es wird immer wieder zu Anschlägen mit verheerenden Auswirkungen kommen.",
  "Die zunehmende Bedrohung durch Cyber-Angriffe wird dazu führen, dass sich die Welt in eine globale Cyberkriegsführung entwickelt.",
  "Die fortschreitende Automatisierung und Robotik wird dazu führen, dass die meisten Jobs in der Produktion, der Logistik und der Dienstleistungsbranche bald von Maschinen übernommen werden.",
  "Die zunehmende Überwachung und Kontrolle durch Regierungen und Unternehmen wird dazu führen, dass die Freiheit und Privatsphäre der Menschen immer weiter eingeschränkt werden.",
]
