export const thesenteile = {
  subjekt: [
    "Mut ist",
    "Leichtsinn ist",
    "Verantwortung ist",
    "Demokratie ist",
    "Geld ist",
    "Liebe ist",
    "Betrug ist",
    "Freiheit ist",
    "Denken ist",
    "Selbstlosigkeit ist",
    "Egoismus ist",
    "Moral ist",
    "Glück ist",
    "Konsum ist",
    "Das Schicksal ist",
    "Das Leben ist",
    "Unabhängigkeit ist",
    "Gerechtigkeit ist",
    "Der Tod ist",
    "Umweltschutz ist",
    "Das Fernsehen ist",
    "Ein Seitensprung ist",
    "Gewalt ist",
    "Der Sinn des Lebens ist",
    "Leistung ist",
    "Hass ist",
    "Eifersucht ist",
    "Die Kunst ist",
    "Religion ist",
    "Die Jugend ist",
    "Hoffnung ist",
    "Frieden ist",
    "Die Ehe ist",
    "Alles ist",
    "Freundschaft ist",
    "Armut ist",
    "Emanzipation ist",
    "Eine Diät ist",
    "Angst ist",
    "Ungerechtigkeit ist",
    "Rassismus ist",
    "Humor ist",
    "Deutscher Rap ist",
    "Die Lügenpresse ist",
    "Fortpflanzung ist",
    "Schwiegereltern sind",
    "Der Sittenverfall ist",
    "Unser Schulsystem ist",
    "Die Gentrifizierung ist",
    "Ein letztes Bier ist",
  ],
  adverb: [
    "letztlich",
    "sozusagen",
    "am Ende des Tages",
    "quasi",
    "genaugenommen",
    "wirklich",
    "leider",
    "zum Glück",
    "durch die Blume gesagt",
    "rückblickend",
    "voraussichtlich",
    "unter Umständen",
    "erwiesernermaßen",
    "gelinde gesagt",
    "streng genommen",
    "unterm Strich",
    "in gewisser Hinsicht",
    "für viele",
    "unleugbar",
    "von Rechts wegen",
    "primär",
    "irgendwie",
    "sicherlich",
    "von außen betrachtet",
    "schon lange nicht mehr",
    "heutzutage",
    "tatsächlich",
    "in Wahrheit",
    "in Zukunft",
    "bei aller Liebe",
    "praktisch",
    "allenfalls",
    "stückweise",
    "schließlich",
    "an und für sich",
    "bei Lichte gesehen",
    "unwiderleglich",
    "mitnichten",
    "vor allem",
    "auch für Hartgesottene",
    "traurigerweise",
    "für besorgte Bürger",
    "wie man hört",
    "in diesem Sinne",
    "unter Drogeneinfluss",
    "menschlich gesehen",
    "theoretisch",
    "für unsereins",
    "ganz objektiv",
    "in anderen Kulturkreisen",
  ],
  conclusion: [
    "die höchste Tugend",
    "die Basis des Zusammenlebens",
    "eine gesellschaftliche Pflicht",
    "der Anfang allen Übels",
    "das, wofür es sich zu leben lohnt",
    "falsch",
    "zutiefst menschlich",
    "kein Kavaliersdelikt mehr",
    "völlig überschätzt",
    "immer Gabe und Aufgabe zugleich",
    "mit Vorsicht zu genießen",
    "fragwürdig",
    "existenzgefährdend",
    "der Schlüssel zum Glück",
    "eine Frage des Anstandes",
    "jedem selbst überlassen",
    "geil",
    "völlig willkürlich",
    "immer schon vorherbestimmt",
    "alles, was wir haben",
    "ein großes Privileg",
    "nicht mehr haltbar",
    "unsere Rettung",
    "eine Katastrophe",
    "der Anfang vom Ende",
    "noch das geringste Übel",
    "nicht grundfalsch",
    "eine Illusion",
    "unterstes Niveau",
    "ein Geschenk Gottes",
    "bedeutungslos",
    "völlig überholt",
    "doch nur relativ",
    "nur die Spitze des Eisberges",
    "eine große Enttäuschung",
    "erst der Anfang",
    "völlig unabdingbar",
    "echt daneben",
    "eine große Chance",
    "der erste Schritt zur Besserung",
    "das Ziel allen Strebens",
    "eine Frage des richtigen Tons",
    "alles, was bleibt",
    "eine Schwäche",
    "schlimmer als der Tod",
    "ein fataler Fehler",
    "besser als Sex",
    "mein Trost und Halt",
    "nichts wert",
  ],
}
