//layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import NavbarQuiz from "../components/navbarquiz";
import Navbar from "@/components/navbar/TopNav";
import { NextUIProvider } from "@nextui-org/react";
import { SessionProvider } from "next-auth/react"; // SessionProvider importieren
import { ToastContainer } from "react-toastify"; 
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <NextUIProvider>
          <SessionProvider>
            {children}
          </SessionProvider>
        </NextUIProvider>
        <ToastContainer
          position="bottom-right"
          hideProgressBar
          className="z-50"
        />
      </body>
    </html>
  );
}
