export const antwortenRichtig = [
  "Absolut korrekt!",
  "Genau auf den Punkt gebracht!",
  "Genauso ist es!",
  "Exakt richtig!",
  "Völlig richtig erkannt!",
  "Perfekt!",
  "Das hast du wunderbar erkannt!",
  "Du bist auf dem richtigen Weg!",
  "Bingo!",
  "Genau meine Rede!",
  "Das stimmt auf den Punkt!",
  "Du bist ein Ass in diesem Bereich!",
  "Bravo, du hast es!",
  "Du hast voll ins Schwarze getroffen!",
  "Das hast du erfasst!",
  "Hut ab, das ist richtig!",
  "Du bist echt spitze!",
  "Fantastisch, das ist es!",
  "Jawohl, das stimmt!",
  "Du bist ein wahrer Experte!",
  "Das ist die richtige Antwort!",
  "Perfektion erreicht!",
  "Du bist auf dem Geld!",
  "Du bist ein Genie!",
  "Hervorragend erkannt!",
  "Das ist genau die Lösung!",
  "Du bist auf dem neuesten Stand!",
  "Volltreffer, das ist korrekt!",
  "Du hast den Nagel auf den Kopf getroffen!",
  "Das ist genau das, was ich meinte!",
  "Gut gebrüllt Löwe!",
  "SuppiDuppi!",
  "Da hast du wohl den Jackpot geknackt!",
  "Das ist so richtig wie Pommes mit Ketchup.",
  "Du hast gerade den goldenen Wissensnugget gefunden.",
  "Das ist richtig, wie der Regenschirm an einem regnerischen Tag.",
  "Du hast den Nagel auf den Kopf getroffen... des richtigen Hammers.",
  "Das ist wie ein Volltreffer beim Bowling - alle Pins umgeworfen!",
  "Das ist nicht nur richtig, das ist so richtig wie ein Maßband.",
  "Du hast gerade den Goldpokal der Richtigkeit gewonnen.",
  "Das ist so richtig, dass sogar der Taschenrechner applaudieren würde.",
  "Du hast gerade den magischen Wahrheitsknopf gedrückt.",
  "Das ist richtig, wie der perfekte 10er bei einer Bewertungsshow.",
  "Du hast den richtigen Code geknackt - Willkommen im Club!",
  "Das ist so richtig wie Schokolade an einem traurigen Tag.",
  "Du hast das Ziel erreicht und sogar noch den Bonuslevel freigeschaltet.",
  "Das ist wie der Hauptgewinn in der Quizshow - Herzlichen Glückwunsch!",
  "Du hast gerade den richtigen Film ausgewählt und jetzt läuft '100% Richtig'.",
  "Das ist so richtig wie ein Regenbogen nach dem Gewitter.",
  "Du hast dich gerade in die richtige Realität eingeloggt - gut gemacht!",
  "Das ist wie ein perfekter Schachzug, der deinen Gegner sprachlos lässt.",
  "Du hast den Richtigkeitsgrad auf 'Expertenlevel' gesteigert.",
  "Das ist so richtig wie ein Eisbecher an einem heißen Sommertag.",
  "Du hast den richtigen Wegweiser genommen und bist im Land der Korrektheit gelandet.",
  "Das ist so richtig, dass selbst der Faktencheck nichts auszusetzen hat.",
  "Du hast gerade den Richtigkeits-Olympiade-Weltrekord aufgestellt.",
  "Das ist wie eine Antwort, die perfekt in das Puzzle passt.",
  "Du hast die Wahrheit erkannt und bist auf der Seite der Richtigkeit.",
  "Das ist so richtig wie ein Lächeln nach einem Witz.",
  "Du hast das richtige Geheimwort eingegeben und das Tor zur Richtigkeitsfestung geöffnet.",
  "Das ist so richtig wie ein Kreis, der perfekt geschlossen ist.",
  "Du hast gerade den richtigen Zeitpunkt erwischt - alles stimmt!",
  "Das ist so richtig, dass selbst der Zahlenstrahl vor Freude tanzt.",
]
