export const antwortenFalsch = [
  "Da hat wohl jemand die falsche Schokoladenseite erwischt.",
  "Das ist so wahr wie Einhörner auf Fahrrädern.",
  "Du hast dich gerade selbst zum Kapitän der Falschinformation ernannt.",
  "Das ist ungefähr so falsch wie Cowboystiefel bei einer Hochzeit.",
  "Du hast den Nagel auf den Kopf... des Nachbarn getroffen.",
  "Das ist wie versuchen, einen Sechser im Lotto zu bekommen, während du Monopoly spielst.",
  "Das ist nicht nur falsch, das ist so falsch wie ein Dreirad auf der Autobahn.",
  "Du hast gerade den Vogel gezeigt, aber leider war es ein Pinguin.",
  "Das ist ungefähr so falsch wie Socken in Sandalen.",
  "Das ist so falsch, dass selbst Siri 'Nein danke' sagt.",
  "Du hast gerade den falschen Drehmoment eingestellt.",
  "Das ist so falsch wie eine Banane mit Ketchup.",
  "Du hast das Ziel verfehlt, aber es war sowieso eine Attrappe.",
  "Das ist wie versuchen, einen Schneemann in der Wüste zu bauen.",
  "Du hast gerade den falschen Film bestellt, und jetzt läuft 'Fifty Shades of Wrong'.",
  "Das ist so falsch wie ein Dinosaurier im Bürogebäude.",
  "Du hast dich gerade in die falsche Realität eingeloggt.",
  "Das ist wie versuchen, Schach zu spielen, aber mit Monopoly-Geld.",
  "Du hast den Falschheitsgrad auf 'Unendlich' gesteigert.",
  "Das ist so falsch wie eine Katze, die sich als Hund verkleidet.",
  "Du hast den falschen Wegweiser genommen und bist im Land der Absurdität gelandet.",
  "Das ist so falsch, dass selbst der Taschenspieler-Verein dagegen protestieren würde.",
  "Du hast gerade den Falschheits-Olympiade-Weltrekord aufgestellt.",
  "Das ist wie versuchen, das Internet mit einem Teelöffel zu trinken.",
  "Du hast die Wahrheit verfehlt und bist in der Nähe der Galaxie der Unwahrheiten gelandet.",
  "Das ist so falsch wie ein Einhorn, das eine Skijacke trägt.",
  "Du hast das falsche Geheimwort eingegeben und das Tor zur Falschheitsfestung geöffnet.",
  "Das ist ungefähr so falsch wie versuchen, das Quadrat im Kreis zu finden.",
  "Du hast gerade einen rückwärts fliegenden Elefanten gesehen - völlig unwahr.",
  "Das ist so falsch, dass selbst der Zahlenstrahl in die andere Richtung zeigt.",
]
